package com.example.movieapp.model

import com.google.gson.annotations.SerializedName

// 🎯 تمثل كائن "فيلم" راجع من API
data class Movie(
    val id: Int,                        // 🆔 رقم الفيلم
    val title: String?,                 // 🎬 اسم الفيلم
    val overview: String?,              // 📝 ملخص الفيلم
    @SerializedName("poster_path") val posterPath: String?,   // 🖼️ رابط بوستر الفيلم
    @SerializedName("backdrop_path") val backdropPath: String?, // 🎞️ خلفية الفيلم
    @SerializedName("vote_average") val voteAverage: Double?, // ⭐ متوسط التقييم
    @SerializedName("release_date") val releaseDate: String?  // 📅 تاريخ الإصدار
)
